sonar.projectKey=commission_program_fix
sonar.projectName=Commission Program Fix
sonar.projectVersion=1.0.0
sonar.sources=.
sonar.exclusions=node_modules/**,**/*.spec.js,dist/**
sonar.sourceEncoding=UTF-8
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.projectKey=aomsink_Comission_ProgramFix
sonar.organization=aomsink
sonar.sources=.