name: SonarQube Cloud Analysis
on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # จำเป็นต้องดึงประวัติทั้งหมดเพื่อความแม่นยำ
      - name: SonarQube Cloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_SECRET: ${{ secrets.SONAR_SECRET }} # ต้องไปใส่ใน Settings > Secrets ของ GitHub ก่อน
